const places = [
  {
    id: "1",
    name: "Cafe Latte",
    description: "A cozy cafe with the best coffee in town.",
    rating: 4.5,
    reviews: ["Great atmosphere!", "Best coffee ever."],
    isTrending: true,
    isTopRated: false,
    isNearby: true,
    menu: ["Coffee", "Pastries"],
    houseSpecials: ["Vanilla Latte"],
    offers: ["Buy one get one free coffee"],
    bestDeals: [
      { deal: "Buy one get one free coffee", percentageOff: null }
    ],
    image: "https://images.unsplash.com/photo-1516116214684-e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwyMjEyNzN8MHwxfGFsbHwxfHx8fHx8fHx8MTY4MjMzMzc5Mg&ixlib=rb-1.2.1&q=80&w=400",
    category: "Cafes",
    priceRange: 4,
  },
  {
    id: "2",
    name: "The Gourmet Bistro",
    description: "Fine dining with a gourmet twist.",
    rating: 4.8,
    reviews: ["Exquisite dining experience.", "Highly recommend the steak."],
    isTrending: false,
    isTopRated: true,
    isNearby: false,
    menu: ["Steak", "Salmon", "Desserts"],
    houseSpecials: ["Filet Mignon"],
    offers: ["20% off on first visit"],
    bestDeals: [
      { deal: "20% off on first visit", percentageOff: 20 }
    ],
    image: "https://images.unsplash.com/photo-1504674900247-0877dfd5d2e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwyMjEyNzN8MHwxfGFsbHwxfHx8fHx8fHx8MTY4MjMzMzc5Mg&ixlib=rb-1.2.1&q=80&w=400",
    category: "Restaurants",
    priceRange: 5,
  },
  {
    id: "3",
    name: "The Hangout Lounge",
    description: "A relaxing lounge with live music.",
    rating: 4.2,
    reviews: ["Nice place to unwind.", "Great live music on weekends."],
    isTrending: false,
    isTopRated: false,
    isNearby: true,
    menu: ["Cocktails", "Appetizers"],
    houseSpecials: ["Signature Cocktails"],
    offers: ["Happy hour discounts"],
    bestDeals: [
      { deal: "Happy hour discounts", percentageOff: null }
    ],
    image: "https://images.unsplash.com/photo-1506748686214e9df14d4d9d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwyMjEyNzN8MHwxfGFsbHwxfHx8fHx8fHx8MTY4MjMzMzc5Mg&ixlib=rb-1.2.1&q=80&w=400",
    category: "Lounges",
    priceRange: 3,
  },
  {
    id: "4",
    name: "The Sunset Grill",
    description: "A casual spot with great food and views.",
    rating: 4.3,
    reviews: ["Great food with a sunset view.", "A perfect place for a relaxing evening."],
    isTrending: true,
    isTopRated: false,
    isNearby: false,
    menu: ["Burgers", "Salads", "Smoothies"],
    houseSpecials: ["Sunset Burger"],
    offers: ["5% off for groups of 5 or more"],
    bestDeals: [
      { deal: "5% off for groups of 5 or more", percentageOff: 5 }
    ],
    image: "https://images.unsplash.com/photo-1506748686214-6c21a5e67b8c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwyMjEyNzN8MHwxfGFsbHwxfHx8fHx8fHx8MTY4MjMzMzc5Mg&ixlib=rb-1.2.1&q=80&w=400",
    category: "Restaurants",
    priceRange: 4,
  },
  {
    id: "5",
    name: "Artisan Bakery",
    description: "Freshly baked goods every day.",
    rating: 4.7,
    reviews: ["Delicious bread and pastries.", "A must-visit for bakery lovers."],
    isTrending: false,
    isTopRated: true,
    isNearby: true,
    menu: ["Bread", "Cakes", "Cookies"],
    houseSpecials: ["Sourdough Bread"],
    offers: ["Buy two loaves, get one free"],
    bestDeals: [
      { deal: "Buy two loaves, get one free", percentageOff: null }
    ],
    image: "https://images.unsplash.com/photo-1592882287781-8c5e1b3f35b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwyMjEyNzN8MHwxfGFsbHwxfHx8fHx8fHx8MTY4MjMzMzc5Mg&ixlib=rb-1.2.1&q=80&w=400",
    category: "Cafes",
    priceRange: 3,
  },
  {
    id: "6",
    name: "The Epicurean",
    description: "A modern eatery with an extensive menu.",
    rating: 4.6,
    reviews: ["Amazing food and service.", "The chef's specials are a must-try."],
    isTrending: true,
    isTopRated: true,
    isNearby: false,
    menu: ["Pasta", "Seafood", "Desserts"],
    houseSpecials: ["Truffle Pasta"],
    offers: ["10% off on your first order"],
    bestDeals: [
      { deal: "10% off on your first order", percentageOff: 10 }
    ],
    image: "https://images.unsplash.com/photo-1504674900247-0877dfd5d2e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwyMjEyNzN8MHwxfGFsbHwxfHx8fHx8fHx8MTY4MjMzMzc5Mg&ixlib=rb-1.2.1&q=80&w=400",
    category: "Restaurants",
    priceRange: 5,
  },
  {
    id: "7",
    name: "The Cozy Corner",
    description: "A charming spot for tea and pastries.",
    rating: 4.4,
    reviews: ["Wonderful atmosphere and friendly staff.", "The pastries are to die for."],
    isTrending: false,
    isTopRated: true,
    isNearby: true,
    menu: ["Tea", "Pastries", "Sandwiches"],
    houseSpecials: ["Afternoon Tea Set"],
    offers: ["Free tea with a purchase of any pastry"],
    bestDeals: [
      { deal: "Free tea with a purchase of any pastry", percentageOff: null }
    ],
    image: "https://images.unsplash.com/photo-1504674900247-0877dfd5d2e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwyMjEyNzN8MHwxfGFsbHwxfHx8fHx8fHx8MTY4MjMzMzc5Mg&ixlib=rb-1.2.1&q=80&w=400",
    category: "Cafes",
    priceRange: 2,
  },
  {
    id: "8",
    name: "The Urban Bistro",
    description: "A trendy spot with modern cuisine.",
    rating: 4.5,
    reviews: ["Great ambiance and food.", "Perfect for a night out."],
    isTrending: true,
    isTopRated: false,
    isNearby: false,
    menu: ["Burgers", "Salads", "Craft Beers"],
    houseSpecials: ["Urban Burger"],
    offers: ["Buy one drink, get the second half off"],
    bestDeals: [
      { deal: "Buy one drink, get the second half off", percentageOff: 50 }
    ],
    image: "https://images.unsplash.com/photo-1555685812-3345e9dcf0e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MXwyMjEyNzN8MHwxfGFsbHwxfHx8fHx8fHx8MTY4MjMzMzc5Mg&ixlib=rb-1.2.1&q=80&w=400",
    category: "Restaurants",
    priceRange: 4,
  },
];

export default places;
